version: 2
jobs:
  deploy-job:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "9d:25:8d:0a:23:c7:18:61:8a:1c:b5:e3:60:04:6d:87"
  build:
    docker:
      - image: aseelibrahimm/docker-ansible:lts
    steps:
      - checkout
      - setup_remote_docker
     
      - run:
          name: Build and push Docker image
          command: |
            docker build -t nodeapp .
            docker tag nodeapp $DOCKER_LOGIN/nodeapp:$CIRCLE_BUILD_NUM
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker push $DOCKER_LOGIN/nodeapp:$CIRCLE_BUILD_NUM
      - run:
          name: Run Ansible playbook
          command: ansible-playbook -i inventory.yml --private-key=$HOME/.ssh/aws --extra-vars "DOCKER_LOGIN=${DOCKER_LOGIN} CIRCLE_BUILD_NUM=${CIRCLE_BUILD_NUM}" servers.yml
            
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
