version: 2
jobs:
  deploy-job:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "9d:25:8d:0a:23:c7:18:61:8a:1c:b5:e3:60:04:6d:87"
  test:
    docker:
      - image: aseelibrahimm/docker-ansible:lts

  build:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - setup_remote_docker
      # - run:
      #     name: Install Ansible
      #     command: |
      #       sudo apt-get update && sudo apt-get install -y ansible
      - run:
          name: Build and push Docker image
          command: |
            sudo docker build -t nodeapp .
            sudo docker tag nodeapp $DOCKER_LOGIN/nodeapp:$CIRCLE_BUILD_NUM
            sudo docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            sudo docker push $DOCKER_LOGIN/nodeapp:$CIRCLE_BUILD_NUM
      - run:
          name: Run Ansible playbook
          command: ansible-playbook -i inventory.yml --private-key=$HOME/.ssh/aws --extra-vars "DOCKER_LOGIN=${DOCKER_LOGIN} CIRCLE_BUILD_NUM=${CIRCLE_BUILD_NUM}" servers.yml
            
workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
