version: 2
orbs:
  ansible: circleci/ansible@0.1.6

jobs:
  deploy-job:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "9d:25:8d:0a:23:c7:18:61:8a:1c:b5:e3:60:04:6d:87"
  test:
    docker:
      - image: docker:stable

  build:
    executor: aws-ssh-executor
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Install Ansible
          command: |
            sudo apt-get update && sudo apt-get install -y ansible
      - run:
          name: Run Ansible playbook
          command: ansible-playbook -i inventory.yml --private-key=$HOME/.ssh/aws servers.yml
      - run:
          name: Build and push Docker image
          command: |
            docker build -t nodeapp .
            docker tag nodeapp $DOCKER_LOGIN/nodeapp:$CIRCLE_BUILD_NUM
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker push $DOCKER_LOGIN/nodeapp:$CIRCLE_BUILD_NUM

executors:
  aws-ssh-executor:
    machine:
      enabled: true
    working_directory: ~/app
    environment:
      SSH_PRIVATE_KEY: $HOME/.ssh/aws
